point_cloud_topic: "/pico_flexx/points"
map_frame_id: "map"
robot_base_frame_id: "mav_base_link"
robot_pose_with_covariance_topic: "/mavros/vision_pose/pose_cov"
robot_pose_cache_size: 200
track_point_frame_id: "map"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
